/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as BusinessReviewRouteImport } from './routes/business-review'
import { Route as RecoverySummaryRouteImport } from './routes/recovery-summary'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as TestCheckoutRouteImport } from './routes/test-checkout'
import { Route as ApiPublicCronInboxRouteImport } from './routes/api/public/cron/inbox'
import { Route as ApiPublicCronMonitorRouteImport } from './routes/api/public/cron/monitor'
import { Route as ApiPublicCronTickRouteImport } from './routes/api/public/cron/tick'
import { Route as ApiPublicWebhookRazorpayRouteImport } from './routes/api/public/webhook/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessReviewRoute = BusinessReviewRouteImport.update({
  id: '/business-review',
  path: '/business-review',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverySummaryRoute = RecoverySummaryRouteImport.update({
  id: '/recovery-summary',
  path: '/recovery-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCheckoutRoute = TestCheckoutRouteImport.update({
  id: '/test-checkout',
  path: '/test-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronInboxRoute = ApiPublicCronInboxRouteImport.update({
  id: '/api/public/cron/inbox',
  path: '/api/public/cron/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronMonitorRoute = ApiPublicCronMonitorRouteImport.update({
  id: '/api/public/cron/monitor',
  path: '/api/public/cron/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronTickRoute = ApiPublicCronTickRouteImport.update({
  id: '/api/public/cron/tick',
  path: '/api/public/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookRazorpayRoute =
  ApiPublicWebhookRazorpayRouteImport.update({
    id: '/api/public/webhook/razorpay',
    path: '/api/public/webhook/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/business-review': typeof BusinessReviewRoute
  '/recovery-summary': typeof RecoverySummaryRoute
  '/rules': typeof RulesRoute
  '/test-checkout': typeof TestCheckoutRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
  '/api/public/cron/monitor': typeof ApiPublicCronMonitorRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/business-review': typeof BusinessReviewRoute
  '/recovery-summary': typeof RecoverySummaryRoute
  '/rules': typeof RulesRoute
  '/test-checkout': typeof TestCheckoutRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
  '/api/public/cron/monitor': typeof ApiPublicCronMonitorRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/business-review': typeof BusinessReviewRoute
  '/recovery-summary': typeof RecoverySummaryRoute
  '/rules': typeof RulesRoute
  '/test-checkout': typeof TestCheckoutRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
  '/api/public/cron/monitor': typeof ApiPublicCronMonitorRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/webhook/razorpay': typeof ApiPublicWebhookRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-trail'
    | '/business-review'
    | '/recovery-summary'
    | '/rules'
    | '/test-checkout'
    | '/api/public/cron/inbox'
    | '/api/public/cron/monitor'
    | '/api/public/cron/tick'
    | '/api/public/webhook/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-trail'
    | '/business-review'
    | '/recovery-summary'
    | '/rules'
    | '/test-checkout'
    | '/api/public/cron/inbox'
    | '/api/public/cron/monitor'
    | '/api/public/cron/tick'
    | '/api/public/webhook/razorpay'
  id:
    | '__root__'
    | '/'
    | '/audit-trail'
    | '/business-review'
    | '/recovery-summary'
    | '/rules'
    | '/test-checkout'
    | '/api/public/cron/inbox'
    | '/api/public/cron/monitor'
    | '/api/public/cron/tick'
    | '/api/public/webhook/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditTrailRoute: typeof AuditTrailRoute
  BusinessReviewRoute: typeof BusinessReviewRoute
  RecoverySummaryRoute: typeof RecoverySummaryRoute
  RulesRoute: typeof RulesRoute
  TestCheckoutRoute: typeof TestCheckoutRoute
  ApiPublicCronInboxRoute: typeof ApiPublicCronInboxRoute
  ApiPublicCronMonitorRoute: typeof ApiPublicCronMonitorRoute
  ApiPublicCronTickRoute: typeof ApiPublicCronTickRoute
  ApiPublicWebhookRazorpayRoute: typeof ApiPublicWebhookRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-review': {
      id: '/business-review'
      path: '/business-review'
      fullPath: '/business-review'
      preLoaderRoute: typeof BusinessReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-summary': {
      id: '/recovery-summary'
      path: '/recovery-summary'
      fullPath: '/recovery-summary'
      preLoaderRoute: typeof RecoverySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-checkout': {
      id: '/test-checkout'
      path: '/test-checkout'
      fullPath: '/test-checkout'
      preLoaderRoute: typeof TestCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/inbox': {
      id: '/api/public/cron/inbox'
      path: '/api/public/cron/inbox'
      fullPath: '/api/public/cron/inbox'
      preLoaderRoute: typeof ApiPublicCronInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/monitor': {
      id: '/api/public/cron/monitor'
      path: '/api/public/cron/monitor'
      fullPath: '/api/public/cron/monitor'
      preLoaderRoute: typeof ApiPublicCronMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tick': {
      id: '/api/public/cron/tick'
      path: '/api/public/cron/tick'
      fullPath: '/api/public/cron/tick'
      preLoaderRoute: typeof ApiPublicCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/razorpay': {
      id: '/api/public/webhook/razorpay'
      path: '/api/public/webhook/razorpay'
      fullPath: '/api/public/webhook/razorpay'
      preLoaderRoute: typeof ApiPublicWebhookRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditTrailRoute: AuditTrailRoute,
  BusinessReviewRoute: BusinessReviewRoute,
  RecoverySummaryRoute: RecoverySummaryRoute,
  RulesRoute: RulesRoute,
  TestCheckoutRoute: TestCheckoutRoute,
  ApiPublicCronInboxRoute: ApiPublicCronInboxRoute,
  ApiPublicCronMonitorRoute: ApiPublicCronMonitorRoute,
  ApiPublicCronTickRoute: ApiPublicCronTickRoute,
  ApiPublicWebhookRazorpayRoute: ApiPublicWebhookRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
